workflows:
  version: 2
  build:
    jobs:
    - node-v10

version: 2
jobs:
  node-base: &node-base
    docker:
    - image: node
    steps:
    - run:
        name: Versions
        command: npm version
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - run:
        name: Lint
        command: npm run lint
    - run:
        name: Test
        command: npm test

  node-v10:
    <<: *node-base
    docker:
    - image: node:10
